name: Archive closed PR branch

on:
  pull_request_target:
    types: [closed, reopened]

jobs:
  archive_pr_branch:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: bencherdev/bencher@main
      - name: Archive closed PR branch with Bencher
        run: |
          bencher archive \
          --project deisa-dask-bencher-test \
          --key "${{ secrets.BENCHER_API_KEY }}" \
          --branch '${{ github.head_ref }}'
