# This workflow removes the benchmark results in Bencher for a PR when it is closed, or restores those benchmark results when the PR is reopened.
name: Archive closed PR branch

on:
  pull_request_target:
    types: [closed, reopened]

jobs:
  archive_pr_branch:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: bencherdev/bencher@main
      - name: Archive closed PR branch with Bencher
        run: |
          bencher archive \
          --project deisa-dask-bencher-test \
          --key "${{ secrets.BENCHER_API_KEY }}" \
          --branch "${{ github.head_ref }}"
